# Generated by Django 6.0.4 on 2026-04-22 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(default='Rice', max_length=100)),
                ('field_acres', models.FloatField(default=1.0)),
                ('sowing_date', models.DateField()),
                ('expected_harvest', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='growthprediction',
            name='predicted_yield',
        ),
        migrations.AddField(
            model_name='growthprediction',
            name='model_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthprediction',
            name='predicted_yield_per_acre',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plantimage',
            name='greenness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantimage',
            name='model_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantimage',
            name='slot',
            field=models.CharField(default='morning', max_length=10),
        ),
        migrations.CreateModel(
            name='DailyGrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('auto', 'Auto (IoT only)')], default='morning', max_length=10)),
                ('day_number', models.IntegerField(default=1)),
                ('actual_height_cm', models.FloatField(blank=True, null=True)),
                ('actual_greenness_score', models.FloatField(blank=True, null=True)),
                ('image_uploaded', models.BooleanField(default=False)),
                ('predicted_height_cm', models.FloatField(blank=True, null=True)),
                ('predicted_yield_per_acre', models.FloatField(blank=True, null=True)),
                ('health_score', models.FloatField(blank=True, null=True)),
                ('growth_stage', models.CharField(blank=True, max_length=50)),
                ('recommendation', models.TextField(blank=True)),
                ('model_accuracy', models.FloatField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriculture.plantimage')),
                ('sensor_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriculture.sensordata')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='agriculture.cropsession')),
            ],
            options={
                'ordering': ['date', 'slot'],
                'unique_together': {('session', 'date', 'slot')},
            },
        ),
    ]
